using System.IO;
using azuretest_2.App.CommonAppLayer.Extensions;

namespace azuretest_2.App.CommonAppLayer.DTOs
{
   
    public class FileDtos
    {
        public Stream Content { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }

        public string GetPathWithFileName()
        {
            string uniqueAutoGeneratedFileName = Path.GetRandomFileName();
            string shortClientSideFileNameWithoutExt = Path.GetFileNameWithoutExtension(Name).TruncateLongString(10);  //Trimming to max 10 as client side file name can be too long
            string ext = Path.GetExtension(Name);
            string basePath = "user1/stories/";

            return basePath + uniqueAutoGeneratedFileName + "_blobimage_" + shortClientSideFileNameWithoutExt + ext;
        }
    }
}